set -g prefix C-w
unbind C-b
bind C-w send-prefix

setw -g mode-keys vi
set -s escape-time 0
bind -n Escape copy-mode

bind h split-window -v
bind v split-window -h

#bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
#bind l select-pane -R

set -g mouse on
set -g default-terminal "screen-256color"
set -g history-limit 100000
# clipboard
set -g set-clipboard on
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard -in"
bind -T copy-mode-vi v send-keys -X begin-selection

bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded
